### ISSUE TITLE
Invalid @minecraft/server and @minecraft/server-ui version for 1.21.20

### ISSUE THREAD

**Issue by lic95** [Dream23322/Isolate-Anticheat#4]
In the newest update 1.21.20, @minecraft/server version 1.12.0-beta and @minecraft/server-ui version 1.2.0-beta do not work (for me atleast).

For the newest update, change the manifest.json dependencies to this:

"dependencies": [{
	"module_name": "@minecraft/server",
	"version": "1.14.0-beta"
},
{
	"module_name": "@minecraft/server-ui",
	"version": "1.3.0-beta"

**Comment by Dream23322** [comment]
This was fixed this week
